"""Surah metadata — GENERATED FILE, do not edit by hand.

Generated by scripts/generate_surah_data.py from https://api.alquran.cloud/v1/surah

Urdu names and revelation order are absent from the source and are
therefore None rather than guessed.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Surah:
    number: int
    name_ar: str
    name_ar_plain: str
    name_en_translit: str
    name_en: str
    ayah_count: int
    revelation_place: str


SURAHS: tuple[Surah, ...] = (
    Surah(1, 'ٱلْفَاتِحَةِ', 'الفاتحه', 'Al-Faatiha', 'The Opening', 7, 'MECCAN'),
    Surah(2, 'البَقَرَةِ', 'البقره', 'Al-Baqara', 'The Cow', 286, 'MEDINAN'),
    Surah(3, 'آلِ عِمۡرَانَ', 'ال عمران', 'Aal-i-Imraan', 'The Family of Imraan', 200, 'MEDINAN'),
    Surah(4, 'النِّسَاءِ', 'النسا', 'An-Nisaa', 'The Women', 176, 'MEDINAN'),
    Surah(5, 'المَائـِدَةِ', 'المايده', 'Al-Maaida', 'The Table', 120, 'MEDINAN'),
    Surah(6, 'الأَنۡعَامِ', 'الانعام', "Al-An'aam", 'The Cattle', 165, 'MECCAN'),
    Surah(7, 'الأَعۡرَافِ', 'الاعراف', "Al-A'raaf", 'The Heights', 206, 'MECCAN'),
    Surah(8, 'الأَنفَالِ', 'الانفال', 'Al-Anfaal', 'The Spoils of War', 75, 'MEDINAN'),
    Surah(9, 'التَّوۡبَةِ', 'التوبه', 'At-Tawba', 'The Repentance', 129, 'MEDINAN'),
    Surah(10, 'يُونُسَ', 'يونس', 'Yunus', 'Jonas', 109, 'MECCAN'),
    Surah(11, 'هُودٍ', 'هود', 'Hud', 'Hud', 123, 'MECCAN'),
    Surah(12, 'يُوسُفَ', 'يوسف', 'Yusuf', 'Joseph', 111, 'MECCAN'),
    Surah(13, 'الرَّعۡدِ', 'الرعد', "Ar-Ra'd", 'The Thunder', 43, 'MEDINAN'),
    Surah(14, 'إِبۡرَاهِيمَ', 'ابراهيم', 'Ibrahim', 'Abraham', 52, 'MECCAN'),
    Surah(15, 'الحِجۡرِ', 'الحجر', 'Al-Hijr', 'The Rock', 99, 'MECCAN'),
    Surah(16, 'النَّحۡلِ', 'النحل', 'An-Nahl', 'The Bee', 128, 'MECCAN'),
    Surah(17, 'الإِسۡرَاءِ', 'الاسرا', 'Al-Israa', 'The Night Journey', 111, 'MECCAN'),
    Surah(18, 'الكَهۡفِ', 'الكهف', 'Al-Kahf', 'The Cave', 110, 'MECCAN'),
    Surah(19, 'مَرۡيَمَ', 'مريم', 'Maryam', 'Mary', 98, 'MECCAN'),
    Surah(20, 'طه', 'طه', 'Taa-Haa', 'Taa-Haa', 135, 'MECCAN'),
    Surah(21, 'الأَنبِيَاءِ', 'الانبيا', 'Al-Anbiyaa', 'The Prophets', 112, 'MECCAN'),
    Surah(22, 'الحَجِّ', 'الحج', 'Al-Hajj', 'The Pilgrimage', 78, 'MEDINAN'),
    Surah(23, 'المُؤۡمِنُونَ', 'المومنون', 'Al-Muminoon', 'The Believers', 118, 'MECCAN'),
    Surah(24, 'النُّورِ', 'النور', 'An-Noor', 'The Light', 64, 'MEDINAN'),
    Surah(25, 'الفُرۡقَانِ', 'الفرقان', 'Al-Furqaan', 'The Criterion', 77, 'MECCAN'),
    Surah(26, 'الشُّعَرَاءِ', 'الشعرا', "Ash-Shu'araa", 'The Poets', 227, 'MECCAN'),
    Surah(27, 'النَّمۡلِ', 'النمل', 'An-Naml', 'The Ant', 93, 'MECCAN'),
    Surah(28, 'القَصَصِ', 'القصص', 'Al-Qasas', 'The Stories', 88, 'MECCAN'),
    Surah(29, 'العَنكَبُوتِ', 'العنكبوت', 'Al-Ankaboot', 'The Spider', 69, 'MECCAN'),
    Surah(30, 'الرُّومِ', 'الروم', 'Ar-Room', 'The Romans', 60, 'MECCAN'),
    Surah(31, 'لُقۡمَانَ', 'لقمان', 'Luqman', 'Luqman', 34, 'MECCAN'),
    Surah(32, 'السَّجۡدَةِ', 'السجده', 'As-Sajda', 'The Prostration', 30, 'MECCAN'),
    Surah(33, 'الأَحۡزَابِ', 'الاحزاب', 'Al-Ahzaab', 'The Clans', 73, 'MEDINAN'),
    Surah(34, 'سَبَإٍ', 'سبا', 'Saba', 'Sheba', 54, 'MECCAN'),
    Surah(35, 'فَاطِرٍ', 'فاطر', 'Faatir', 'The Originator', 45, 'MECCAN'),
    Surah(36, 'يسٓ', 'يس', 'Yaseen', 'Yaseen', 83, 'MECCAN'),
    Surah(37, 'الصَّافَّاتِ', 'الصافات', 'As-Saaffaat', 'Those drawn up in Ranks', 182, 'MECCAN'),
    Surah(38, 'صٓ', 'ص', 'Saad', 'The letter Saad', 88, 'MECCAN'),
    Surah(39, 'الزُّمَرِ', 'الزمر', 'Az-Zumar', 'The Groups', 75, 'MECCAN'),
    Surah(40, 'غَافِرٍ', 'غافر', 'Ghafir', 'The Forgiver', 85, 'MECCAN'),
    Surah(41, 'فُصِّلَتۡ', 'فصلت', 'Fussilat', 'Explained in detail', 54, 'MECCAN'),
    Surah(42, 'الشُّورَىٰ', 'الشوري', 'Ash-Shura', 'Consultation', 53, 'MECCAN'),
    Surah(43, 'الزُّخۡرُفِ', 'الزخرف', 'Az-Zukhruf', 'Ornaments of gold', 89, 'MECCAN'),
    Surah(44, 'الدُّخَانِ', 'الدخان', 'Ad-Dukhaan', 'The Smoke', 59, 'MECCAN'),
    Surah(45, 'الجَاثِيَةِ', 'الجاثيه', 'Al-Jaathiya', 'Crouching', 37, 'MECCAN'),
    Surah(46, 'الأَحۡقَافِ', 'الاحقاف', 'Al-Ahqaf', 'The Dunes', 35, 'MECCAN'),
    Surah(47, 'مُحَمَّدٍ', 'محمد', 'Muhammad', 'Muhammad', 38, 'MEDINAN'),
    Surah(48, 'الفَتۡحِ', 'الفتح', 'Al-Fath', 'The Victory', 29, 'MEDINAN'),
    Surah(49, 'الحُجُرَاتِ', 'الحجرات', 'Al-Hujuraat', 'The Inner Apartments', 18, 'MEDINAN'),
    Surah(50, 'قٓ', 'ق', 'Qaaf', 'The letter Qaaf', 45, 'MECCAN'),
    Surah(51, 'الذَّارِيَاتِ', 'الذاريات', 'Adh-Dhaariyat', 'The Winnowing Winds', 60, 'MECCAN'),
    Surah(52, 'الطُّورِ', 'الطور', 'At-Tur', 'The Mount', 49, 'MECCAN'),
    Surah(53, 'النَّجۡمِ', 'النجم', 'An-Najm', 'The Star', 62, 'MECCAN'),
    Surah(54, 'القَمَرِ', 'القمر', 'Al-Qamar', 'The Moon', 55, 'MECCAN'),
    Surah(55, 'الرَّحۡمَٰن', 'الرحمن', 'Ar-Rahmaan', 'The Beneficent', 78, 'MEDINAN'),
    Surah(56, 'الوَاقِعَةِ', 'الواقعه', 'Al-Waaqia', 'The Inevitable', 96, 'MECCAN'),
    Surah(57, 'الحَدِيدِ', 'الحديد', 'Al-Hadid', 'The Iron', 29, 'MEDINAN'),
    Surah(58, 'المُجَادلَةِ', 'المجادله', 'Al-Mujaadila', 'The Pleading Woman', 22, 'MEDINAN'),
    Surah(59, 'الحَشۡرِ', 'الحشر', 'Al-Hashr', 'The Exile', 24, 'MEDINAN'),
    Surah(60, 'المُمۡتَحنَةِ', 'الممتحنه', 'Al-Mumtahana', 'She that is to be examined', 13, 'MEDINAN'),
    Surah(61, 'الصَّفِّ', 'الصف', 'As-Saff', 'The Ranks', 14, 'MEDINAN'),
    Surah(62, 'الجُمُعَةِ', 'الجمعه', "Al-Jumu'a", 'Friday', 11, 'MEDINAN'),
    Surah(63, 'المُنَافِقُونَ', 'المنافقون', 'Al-Munaafiqoon', 'The Hypocrites', 11, 'MEDINAN'),
    Surah(64, 'التَّغَابُنِ', 'التغابن', 'At-Taghaabun', 'Mutual Disillusion', 18, 'MEDINAN'),
    Surah(65, 'الطَّلَاقِ', 'الطلاق', 'At-Talaaq', 'Divorce', 12, 'MEDINAN'),
    Surah(66, 'التَّحۡرِيمِ', 'التحريم', 'At-Tahrim', 'The Prohibition', 12, 'MEDINAN'),
    Surah(67, 'المُلۡكِ', 'الملك', 'Al-Mulk', 'The Sovereignty', 30, 'MECCAN'),
    Surah(68, 'القَلَمِ', 'القلم', 'Al-Qalam', 'The Pen', 52, 'MECCAN'),
    Surah(69, 'الحَاقَّةِ', 'الحاقه', 'Al-Haaqqa', 'The Reality', 52, 'MECCAN'),
    Surah(70, 'المَعَارِجِ', 'المعارج', "Al-Ma'aarij", 'The Ascending Stairways', 44, 'MECCAN'),
    Surah(71, 'نُوحٍ', 'نوح', 'Nooh', 'Noah', 28, 'MECCAN'),
    Surah(72, 'الجِنِّ', 'الجن', 'Al-Jinn', 'The Jinn', 28, 'MECCAN'),
    Surah(73, 'المُزَّمِّلِ', 'المزمل', 'Al-Muzzammil', 'The Enshrouded One', 20, 'MECCAN'),
    Surah(74, 'المُدَّثِّرِ', 'المدثر', 'Al-Muddaththir', 'The Cloaked One', 56, 'MECCAN'),
    Surah(75, 'القِيَامَةِ', 'القيامه', 'Al-Qiyaama', 'The Resurrection', 40, 'MECCAN'),
    Surah(76, 'الإِنسَانِ', 'الانسان', 'Al-Insaan', 'Man', 31, 'MEDINAN'),
    Surah(77, 'المُرۡسَلَاتِ', 'المرسلات', 'Al-Mursalaat', 'The Emissaries', 50, 'MECCAN'),
    Surah(78, 'النَّبَإِ', 'النبا', 'An-Naba', 'The Announcement', 40, 'MECCAN'),
    Surah(79, 'النَّازِعَاتِ', 'النازعات', "An-Naazi'aat", 'Those who drag forth', 46, 'MECCAN'),
    Surah(80, 'عَبَسَ', 'عبس', 'Abasa', 'He frowned', 42, 'MECCAN'),
    Surah(81, 'التَّكۡوِيرِ', 'التكوير', 'At-Takwir', 'The Overthrowing', 29, 'MECCAN'),
    Surah(82, 'الانفِطَارِ', 'الانفطار', 'Al-Infitaar', 'The Cleaving', 19, 'MECCAN'),
    Surah(83, 'المُطَفِّفِينَ', 'المطففين', 'Al-Mutaffifin', 'Defrauding', 36, 'MECCAN'),
    Surah(84, 'الانشِقَاقِ', 'الانشقاق', 'Al-Inshiqaaq', 'The Splitting Open', 25, 'MECCAN'),
    Surah(85, 'البُرُوجِ', 'البروج', 'Al-Burooj', 'The Constellations', 22, 'MECCAN'),
    Surah(86, 'الطَّارِقِ', 'الطارق', 'At-Taariq', 'The Morning Star', 17, 'MECCAN'),
    Surah(87, 'الأَعۡلَىٰ', 'الاعلي', "Al-A'laa", 'The Most High', 19, 'MECCAN'),
    Surah(88, 'الغَاشِيَةِ', 'الغاشيه', 'Al-Ghaashiya', 'The Overwhelming', 26, 'MECCAN'),
    Surah(89, 'الفَجۡرِ', 'الفجر', 'Al-Fajr', 'The Dawn', 30, 'MECCAN'),
    Surah(90, 'البَلَدِ', 'البلد', 'Al-Balad', 'The City', 20, 'MECCAN'),
    Surah(91, 'الشَّمۡسِ', 'الشمس', 'Ash-Shams', 'The Sun', 15, 'MECCAN'),
    Surah(92, 'اللَّيۡلِ', 'الليل', 'Al-Lail', 'The Night', 21, 'MECCAN'),
    Surah(93, 'الضُّحَىٰ', 'الضحي', 'Ad-Dhuhaa', 'The Morning Hours', 11, 'MECCAN'),
    Surah(94, 'الشَّرۡحِ', 'الشرح', 'Ash-Sharh', 'The Consolation', 8, 'MECCAN'),
    Surah(95, 'التِّينِ', 'التين', 'At-Tin', 'The Fig', 8, 'MECCAN'),
    Surah(96, 'العَلَقِ', 'العلق', 'Al-Alaq', 'The Clot', 19, 'MECCAN'),
    Surah(97, 'القَدۡرِ', 'القدر', 'Al-Qadr', 'The Power, Fate', 5, 'MECCAN'),
    Surah(98, 'البَيِّنَةِ', 'البينه', 'Al-Bayyina', 'The Evidence', 8, 'MEDINAN'),
    Surah(99, 'الزَّلۡزَلَةِ', 'الزلزله', 'Az-Zalzala', 'The Earthquake', 8, 'MEDINAN'),
    Surah(100, 'العَادِيَاتِ', 'العاديات', 'Al-Aadiyaat', 'The Chargers', 11, 'MECCAN'),
    Surah(101, 'القَارِعَةِ', 'القارعه', "Al-Qaari'a", 'The Calamity', 11, 'MECCAN'),
    Surah(102, 'التَّكَاثُرِ', 'التكاثر', 'At-Takaathur', 'Competition', 8, 'MECCAN'),
    Surah(103, 'العَصۡرِ', 'العصر', 'Al-Asr', 'The Declining Day, Epoch', 3, 'MECCAN'),
    Surah(104, 'الهُمَزَةِ', 'الهمزه', 'Al-Humaza', 'The Traducer', 9, 'MECCAN'),
    Surah(105, 'الفِيلِ', 'الفيل', 'Al-Fil', 'The Elephant', 5, 'MECCAN'),
    Surah(106, 'قُرَيۡشٍ', 'قريش', 'Quraish', 'Quraysh', 4, 'MECCAN'),
    Surah(107, 'المَاعُونِ', 'الماعون', "Al-Maa'un", 'Almsgiving', 7, 'MECCAN'),
    Surah(108, 'الكَوۡثَرِ', 'الكوثر', 'Al-Kawthar', 'Abundance', 3, 'MECCAN'),
    Surah(109, 'الكَافِرُونَ', 'الكافرون', 'Al-Kaafiroon', 'The Disbelievers', 6, 'MECCAN'),
    Surah(110, 'النَّصۡرِ', 'النصر', 'An-Nasr', 'Divine Support', 3, 'MEDINAN'),
    Surah(111, 'المَسَدِ', 'المسد', 'Al-Masad', 'The Palm Fibre', 5, 'MECCAN'),
    Surah(112, 'الإِخۡلَاصِ', 'الاخلاص', 'Al-Ikhlaas', 'Sincerity', 4, 'MECCAN'),
    Surah(113, 'الفَلَقِ', 'الفلق', 'Al-Falaq', 'The Dawn', 5, 'MECCAN'),
    Surah(114, 'النَّاسِ', 'الناس', 'An-Naas', 'Mankind', 6, 'MECCAN'),
)

SURAH_BY_NUMBER: dict[int, Surah] = {s.number: s for s in SURAHS}

#: Total ayah count across the mushaf, derived from the table above.
TOTAL_AYAHS: int = sum(s.ayah_count for s in SURAHS)
