"""Generate Surah metadata from a fetched source.

Run:
    curl -s https://api.alquran.cloud/v1/surah -o data/quran/surah_list.json
    python scripts/generate_surah_data.py

Writes:
    backend/tafahhum/quran/surah_data.py     (in-process lookup table)
    backend/migrations/006_surah_seed.sql    (database seed)

Surah metadata is generated from a source and never hand-typed, so that the
ayah counts and names in the code are traceable to something rather than
reconstructed from memory. Fields the source does not provide (Urdu names,
revelation order) are emitted as None rather than guessed.
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from tafahhum.arabic.normalize import normalize_key  # noqa: E402

SOURCE = ROOT / "data" / "quran" / "surah_list.json"
PY_OUT = ROOT / "backend" / "tafahhum" / "quran" / "surah_data.py"
SQL_OUT = ROOT / "backend" / "migrations" / "006_surah_seed.sql"

SOURCE_ATTRIBUTION = "https://api.alquran.cloud/v1/surah"


def sql_str(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    if not SOURCE.exists():
        print(f"missing {SOURCE}; fetch it first (see module docstring)", file=sys.stderr)
        return 1

    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    if payload.get("code") != 200:
        print(f"source returned code {payload.get('code')}", file=sys.stderr)
        return 1

    surahs = payload["data"]
    if len(surahs) != 114:
        print(f"expected 114 surahs, source gave {len(surahs)}", file=sys.stderr)
        return 1

    rows = []
    for s in surahs:
        name_ar = s["name"]
        # The source prefixes every name with "سُورَةُ"; strip it so the stored
        # name is the surah name itself and matching is not thrown by the prefix.
        for prefix in ("سُورَةُ ", "سُورَة ", "سورة "):
            if name_ar.startswith(prefix):
                name_ar = name_ar[len(prefix):]
                break
        rows.append(
            {
                "number": s["number"],
                "name_ar": name_ar,
                "name_ar_plain": normalize_key(name_ar),
                "name_en_translit": s["englishName"],
                "name_en": s["englishNameTranslation"],
                "ayah_count": s["numberOfAyahs"],
                "revelation_place": "MECCAN" if s["revelationType"] == "Meccan" else "MEDINAN",
            }
        )

    _write_python(rows)
    _write_sql(rows)
    total = sum(r["ayah_count"] for r in rows)
    print(f"wrote {len(rows)} surahs, {total} ayahs total")
    print(f"  {PY_OUT.relative_to(ROOT)}")
    print(f"  {SQL_OUT.relative_to(ROOT)}")
    return 0


def _write_python(rows: list[dict]) -> None:
    out = io.StringIO()
    out.write('"""Surah metadata — GENERATED FILE, do not edit by hand.\n\n')
    out.write(f"Generated by scripts/generate_surah_data.py from {SOURCE_ATTRIBUTION}\n\n")
    out.write("Urdu names and revelation order are absent from the source and are\n")
    out.write("therefore None rather than guessed.\n")
    out.write('"""\n\n')
    out.write("from __future__ import annotations\n\n")
    out.write("from dataclasses import dataclass\n\n\n")
    out.write("@dataclass(frozen=True)\n")
    out.write("class Surah:\n")
    out.write("    number: int\n")
    out.write("    name_ar: str\n")
    out.write("    name_ar_plain: str\n")
    out.write("    name_en_translit: str\n")
    out.write("    name_en: str\n")
    out.write("    ayah_count: int\n")
    out.write("    revelation_place: str\n\n\n")
    out.write("SURAHS: tuple[Surah, ...] = (\n")
    for r in rows:
        out.write(
            "    Surah({number}, {name_ar!r}, {name_ar_plain!r}, "
            "{name_en_translit!r}, {name_en!r}, {ayah_count}, {revelation_place!r}),\n".format(**r)
        )
    out.write(")\n\n")
    out.write("SURAH_BY_NUMBER: dict[int, Surah] = {s.number: s for s in SURAHS}\n\n")
    out.write("#: Total ayah count across the mushaf, derived from the table above.\n")
    out.write("TOTAL_AYAHS: int = sum(s.ayah_count for s in SURAHS)\n")
    PY_OUT.write_text(out.getvalue(), encoding="utf-8")


def _write_sql(rows: list[dict]) -> None:
    out = io.StringIO()
    out.write("-- 006_surah_seed.sql — GENERATED FILE, do not edit by hand.\n")
    out.write(f"-- Generated by scripts/generate_surah_data.py from {SOURCE_ATTRIBUTION}\n")
    out.write("-- Urdu names and revelation order are not provided by the source and\n")
    out.write("-- are left NULL rather than guessed.\n\n")
    out.write(
        "INSERT INTO surah "
        "(number, name_ar, name_ar_plain, name_en, name_en_translit, "
        "name_ur, meaning_en, ayah_count, revelation_place, revelation_order)\nVALUES\n"
    )
    lines = []
    for r in rows:
        lines.append(
            "    ({}, {}, {}, {}, {}, NULL, {}, {}, {}, NULL)".format(
                r["number"],
                sql_str(r["name_ar"]),
                sql_str(r["name_ar_plain"]),
                sql_str(r["name_en"]),
                sql_str(r["name_en_translit"]),
                sql_str(r["name_en"]),
                r["ayah_count"],
                sql_str(r["revelation_place"]),
            )
        )
    out.write(",\n".join(lines))
    out.write("\nON CONFLICT (number) DO NOTHING;\n")
    SQL_OUT.write_text(out.getvalue(), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
